version: "3.7"

services:    
  backtend_website_template:
    container_name: bwt
    # build: .
    image: backtend_website_template_image
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - migration
    networks:
      - backend

  migration:
    container_name: bwt_migration
    build: .
    image: backtend_website_template_image
    command: python3 manage.py migrate
    volumes:
      - .:/usr/src/app/
    depends_on:
      - make_migrations
    networks:
      - backend

  make_migrations:
    container_name: bwt_make_migrations
    build: .
    image: backtend_website_template_image
    command: python3 manage.py makemigrations
    volumes:
      - .:/usr/src/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge