version: "3.7"

services:    
  mongodb:
    container_name: bwt_mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./local_db/db_backup/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./local_db/db_backup/dump:/dump
    command: mongod --quiet --logpath /dev/null
    networks:
      - backend

  # mongodb_student:
  #   container_name: bwt_mongodb_student
  #   image: mongo
  #   restart: unless-stopped
  #   ports:
  #     - 27019:27017
  #   volumes:
  #     - ./local_db/db_backup/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
  #     - ./local_db/db_backup/dump:/dump
  #   command: mongod --quiet --logpath /dev/null
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge