version: "3.7"

services:    
  mongodb:
    container_name: bwt_mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - ./local_db/db_backup/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./local_db/db_backup/dump:/dump
    command: mongod --quiet --logpath /dev/null
    networks:
      - backend

  # mongodb_student:
  #   container_name: bwt_mongodb_student
  #   image: mongo
  #   restart: unless-stopped
  #   ports:
  #     - 27019:27017
  #   volumes:
  #     - ./local_db/db_backup/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
  #     - ./local_db/db_backup/dump:/dump
  #   command: mongod --quiet --logpath /dev/null
  #   networks:
  #     - backend
  
  backtend_website_template:
    container_name: bwt
    # build: .
    image: backtend_website_template_image
    restart: unless-stopped
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - migration
    networks:
      - backend

  migration:
    container_name: bwt_migration
    build: .
    image: backtend_website_template_image
    command: python3 manage.py migrate
    volumes:
      - .:/usr/src/app/
    depends_on:
      - make_migrations
    networks:
      - backend

  make_migrations:
    container_name: bwt_make_migrations
    build: .
    image: backtend_website_template_image
    command: python3 manage.py makemigrations
    volumes:
      - .:/usr/src/app/
    depends_on:
      - mongodb
      # - mongodb_student
    networks:
      - backend

networks:
  backend:
    driver: bridge