version: "3.7"

services:    
  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ./db_backup/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./db_backup/dump:/dump
    # environment:
    #   - MONGO_INITDB_DATABASE=estagio_hoje
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin
    command: mongod --quiet --logpath /dev/null